### PR TITLE
Fix/tally votes trustee threshold

### LINKED ISSUE #58: Passing only Threshold amount of Trustees causes crash
## Bug Report

**Current Behavior**
If only the threshold amount of trustees is passed in, application crashes. 

The call to the `tallyvotes` method needs to send over all the trusteeKeys in the 2nd parameter (not just the ones that are present) and the 3rd parameter represents the number of trustees that are actually present for the decryption. (w/ threshold already set in the api config sent in the 1st parameter) So with this set up, the an API will have to do the actual validation that the number of trustees announced has reached the appropriate threshold number before calling the TallyVotes method

**Expected behavior/code**
Only the threshold amount of trustees should be necessary for encryption and application should not crash.

### PR DESCRIPTION
**Pull request by AddressXception**
### Checklist
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] 🤔 **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] ✅ **DO** check open PR's to avoid duplicates.
- [x] ✅ **DO** keep pull requests small so they can be easily reviewed.
- [ ] ✅ **DO** build locally before pushing.
- [ ] ✅ **DO** make sure tests pass.
- [ ] ✅ **DO** make sure any new changes are documented.
- [ ] ✅ **DO** make sure not to introduce any compiler warnings.
- [ ] ❌**AVOID** breaking the continuous integration build.
- [ ] ❌**AVOID** making significant changes to the overall architecture.

### Description

Fixes #58 

Allows the API interaction pattern to pass in any number of trustees in order to do decryption.  Trustees must be greater than threshold.

#### To Test:
1. execute the `examples/api` sample
2. Expected: tests pass

💔Thank you!

### CODE REVIEW

File: src/electionguard/api/tally_votes.c [hunk 1]
```diff
@@ -143,7 +136,7 @@ bool initialize_trustees(struct trustee_state *trustee_states)
         if (result.status != DECRYPTION_TRUSTEE_SUCCESS)
             ok = false;
         else
-            trustees[i] = result.decryptor;
+            decryption_trustees[result.trustee_index] = result.decryptor;
```
Comment (AddressXception) [inline src/electionguard/api/tally_votes.c:139]: since most of the internals of this lib expect things to be index based and in the right order, by assigning the trustee to it's expected spot in the `decryption_trustees` array, we side-step having to do lookups in other parts of the code

File: src/electionguard/api/tally_votes.c [hunk 2]
```diff
@@ -214,20 +213,52 @@ bool decrypt_tally_shares(uint32_t num_decrypting_trustees)
     return ok;
 }
 
+bool request_missing_trustee_tally_shares(
```
Comment (AddressXception) [inline src/electionguard/api/tally_votes.c:216]: this is just a move refactor

File: src/electionguard/decryption/trustee.c [hunk 3]
```diff
@@ -124,21 +125,21 @@ Decryption_Trustee_new(uint32_t num_trustees, uint32_t threshold,
     return result;
 }
 
-void Decryption_Trustee_free(Decryption_Trustee d)
+void Decryption_Trustee_free(Decryption_Trustee decryption_trustee)
```
Comment (AddressXception) [inline src/electionguard/decryption/trustee.c:128]: all changes to this file are only to improve readability and fix spelling errors.  There are no logic changes

**Review by echumley-msft — APPROVED** [review]

File: examples/api/main.c [hunk 4]
```diff
@@ -13,19 +14,27 @@
...
+static bool result_equals_expected_selections(struct test_ballot *testBallots, uint32_t actual_tally, uint32_t selection_index);
 
 // Election Parameters
 uint32_t const NUM_TRUSTEES = 3;
-uint32_t const THRESHOLD = 2;
+uint32_t const THRESHOLD = 2; 
 uint32_t const NUM_ENCRYPTERS = 3;
 uint32_t const NUM_SELECTIONS = 6;
-uint32_t const DECRYPTING_TRUSTEES = 2;
+uint32_t const DECRYPTING_TRUSTEES = 2;             // must be >= THRESHOLD && <= NUM_TRUSTEES
```
Comment (keithrfung) [inline examples/api/main.c:35]: This should be an `assert` instead of just a comment.  They exist later in the code and can have this as an error.

File: examples/api/main.c [hunk 5]
```diff
@@ -13,19 +14,27 @@
 #include <electionguard/api/tally_votes.h>
 #include <electionguard/max_values.h>
 
+struct test_ballot
```
Comment (keithrfung) [inline examples/api/main.c:17]: Not a huge fan of the name `test_ballot` since `ballot` could be used. However, I could be swayed given the intent.

Comment (keithrfung) [reply examples/api/main.c:17]: This would also mean that you could use `id` instead of `ballotId`

File: examples/api/main.c [hunk 6]
```diff
@@ -42,7 +51,7 @@ int main()
     };
 
     // Create Election
-    printf("\n--- Create Election ---\n");
+    printf("\n--- Create Election ---\n\n");
```
Comment (keithrfung) [inline examples/api/main.c:54]: It really feels like this `printf` needs a wrapper function like `print_heading()` in this file that just adds those new lines.

File: src/electionguard/api/tally_votes.c (hunk 2 above)
Comment (keithrfung) [reply src/electionguard/api/tally_votes.c:216]: Thanks for denoting that.

File: src/electionguard/api/tally_votes.c [hunk 7]
```diff
@@ -214,20 +213,52 @@ bool decrypt_tally_shares(uint32_t num_decrypting_trustees)
...
 
+            // if the decryption trustee at the index is null, then they have not announced
+            if (decryption_trustees[i] == NULL)
+                ok = false;
+
+            struct decryption_fragments decryption_fragments = {.bytes = NULL};
             {
                 struct Decryption_Trustee_compute_fragments_r result =
-                    Decryption_Trustee_compute_fragments(trustees[i],
+                    Decryption_Trustee_compute_fragments(decryption_trustees[i],
```
Comment (keithrfung) [inline src/electionguard/api/tally_votes.c:261]: This denotation was needed. Thanks for adding.

File: src/electionguard/decryption/trustee.c [hunk 8]
```diff
@@ -318,7 +320,7 @@ Decryption_Trustee_compute_share(Decryption_Trustee d)
 }
 //auxilary functions
 
-size_t compute_size_of_available_trusties(const bool *requested,
+size_t compute_size_of_available_trustees(const bool *requested,
```
Comment (keithrfung) [inline src/electionguard/decryption/trustee.c:323]: Never noticed the misspelling. Glad it's fixed.

**Review by keithrfung — CHANGES_REQUESTED** [review]
Small couple changes
