### PR TITLE
Use BCrypt for get byte on windows

### LINKED ISSUE #85: Fix return on RandomSouce_get_byte function
## Bug Report
The RandomSource_get_byte function
https://github.com/microsoft/electionguard-c/blob/75a2e66b804d7df1611a9416919c269e5cbe06bd/src/electionguard/random_source.c#L61
in electionguard-c always returns number "1" on the Windows platform.
It is used in  generate_keys
https://github.com/microsoft/electionguard-c/blob/75a2e66b804d7df1611a9416919c269e5cbe06bd/src/electionguard/rsa.c#L40
And so on.
This issue possibly allows disclosing Trustees' RSA keys. The behavior of the RandomSource_get_byte is obviously invalid.
src/electionguard/random_source.c:61
<https://github.com/microsoft/electionguard-c|microsoft/electionguard-c>microsoft/electionguard-c | Added by GitHub
src/electionguard/rsa.c:40
<https://github.com/microsoft/electionguard-c|microsoft/electionguard-c>microsoft/electionguard-c | Added by GitHub

### PR DESCRIPTION
**Pull request by AddressXception**
### Issue

Fixes #85 

### Description
use Bcrypt on windows to generate random bytes.  Refactor the api to support returning an enum and filling an out parameter, as is consistent with other api's in the file.  This method signature change is consumed in the rsa.c file, and uses an `assert` to check the return code.  While we generally discourage the use of `assert` in application code, this was the most straightforward way to elicit the desired behavior without refactoring the entire method.

### Testing
1. run `makefile -f Makefile.mk run-api` in MSYS on Windows
2. Expected: all tests pass

### Checklist
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] 🤔 **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] ✅ **DO** check open PR's to avoid duplicates.
- [x] ✅ **DO** keep pull requests small so they can be easily reviewed.
- [x] ✅ **DO** build locally before pushing.
- [x] ✅ **DO** make sure tests pass.
- [x] ✅ **DO** make sure any new changes are documented.
- [x] ✅ **DO** make sure not to introduce any compiler warnings.
- [x] ❌**AVOID** breaking the continuous integration build.
- [x] ❌**AVOID** making significant changes to the overall architecture.

💔Thank you!

### CODE REVIEW

File: src/electionguard/random_source.c [hunk 1]
```diff
@@ -58,18 +58,23 @@ void RandomSource_free(RandomSource source)
...
 #ifdef HAVE_BCRYPTGENRANDOM
-    //NTSTATUS ntstatus =
-        //BCryptGenRandom(NULL, &ret, 1, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
-        ret = 1;
+    NTSTATUS ntstatus =
+        BCryptGenRandom(NULL, &ret, 1, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
+
+        if (ntstatus != STATUS_SUCCESS)
+        {
+            result = RANDOM_SOURCE_IO_ERROR;
```
Comment (comcma) [inline src/electionguard/random_source.c]: I would do the `assert` here instead of returning an enum since we only care that BcryptGetRandom is not succeeding.

File: src/electionguard/random_source.c [hunk 2]
```diff
@@ -58,18 +58,23 @@ void RandomSource_free(RandomSource source)
 #endif
 }
 
-uint8_t RandomSource_get_byte(RandomSource source)
+enum RandomSource_status RandomSource_get_byte(RandomSource source, uint8_t ret)
```
Comment (comcma) [inline src/electionguard/random_source.c]: You should undo this function definition change. Right now, you are passing the buffer value, and not the address so nothing is changing on the caller side.

File: src/electionguard/rsa.c [hunk 3]
```diff
@@ -37,7 +37,8 @@ void generate_keys(rsa_private_key* priv_key, rsa_public_key* pub_key)
     /* Select p */
     for(int i = 0; i < BUFFER_SIZE; i++)
     {
-        buffer[i] = RandomSource_get_byte(source) % 0xFF;
+        enum RandomSource_status source_status = RandomSource_get_byte(source, buffer[i]) % 0xFF;
+        assert(source_status == RANDOM_SOURCE_SUCCESS);
```
Comment (comcma) [inline src/electionguard/rsa.c]: `buffer` is a stack-based array in this function that is uninitialized. This call passes in the value at the `i` index of the `buffer` which isn't what we want since we want a random byte to be written to that location in memory. 

Separately, this new call mods off the enum returned which I don't believe is intended.

**Review by comcma — CHANGES_REQUESTED** [review]

File: src/electionguard/rsa.c (hunk 3 above)
Comment (comcma) [reply src/electionguard/rsa.c]: I think going back to the previous function definition and having the random byte returned makes more sense here. The `% 0xFF` should probably be removed regardless since `0xFF % 0xFF` is 0 so we are losing that as a possible random byte value, and now twice as likely to have 0 as opposed to any other byte value.

**Review by keithrfung — APPROVED** [review]
lgtm.
